package com.gamesmall.quienquieresermillonariojavaswing;

import com.gamesmall.daos.PreguntaDaoSinHibernate;
import static com.gamesmall.quienquieresermillonariojavaswing.Program.connection;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JLabel;

public class Window extends javax.swing.JFrame {

    private int numeroPreguntaActual = 1;
    private float valorPreguntaActual;
    private int respuestaCorrecta;
    private float dineroTotalGanado = 0;
    private ResultSet pregunta = null;
    private java.sql.Connection conn = connection.getConnection();

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        setPropertiesWindow();
        try {
            configuring();
        } catch (SQLException ex) {

        }
    }

    private void setPropertiesWindow() {
        setTitle("Quien quiere ser millonario");
        this.setLocationRelativeTo(null);

    }

    private void repaintContent() {
        getContentPane().removeAll();
        repaint();
    }

    private void showTotalPoints() {
        setLayout(new GridLayout(2, 1));
        add(new JLabel("Puntos ganados: " + dineroTotalGanado));
        JButton playAgain = new JButton("Volver a jugar");
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    playAgainActionPerformed(evt);
                } catch (SQLException ex) {
                    System.out.println("exception" + ex.getMessage());
                }
            }
        });
        add(playAgain);
        validate();
    }

    private void configuring() throws SQLException {

        Statement st = conn.createStatement();
        PreguntaDaoSinHibernate pdsh = new PreguntaDaoSinHibernate();
        pregunta = pdsh.obtenerPorId(numeroPreguntaActual);

        if (pregunta.next()) {
            valorPreguntaActual = pregunta.getInt("ValorPregunta");
            enunciado.setText(pregunta.getString("EnunciadoPregunta"));
            enunciado.setSize(pregunta.getString("EnunciadoPregunta").length(), 10);
            ResultSet rs = st.executeQuery(
                    "SELECT r.*, p.* FROM pregunta AS p"
                    + " INNER JOIN respuesta AS r"
                    + " ON r.pregunta_idpregunta = p.idpregunta"
                    + " WHERE p.idpregunta = " + pregunta.getInt("idpregunta")
            );

            if (rs.next()) {
                primeraRespuesta.setText(rs.getInt("OrdenRespuesta") + ". " + rs.getString("DescripcionRespuesta"));
                primeraRespuesta.putClientProperty("Id", rs.getInt("OrdenRespuesta"));
                if (rs.getBoolean("EsCorrecta")) {
                    respuestaCorrecta = rs.getInt("OrdenRespuesta");
                }
            }

            if (rs.next()) {
                segundaRespuesta.setText(rs.getInt("OrdenRespuesta") + ". " + rs.getString("DescripcionRespuesta"));
                segundaRespuesta.putClientProperty("Id", rs.getInt("OrdenRespuesta"));
                if (rs.getBoolean("EsCorrecta")) {
                    respuestaCorrecta = rs.getInt("OrdenRespuesta");
                }
            }
            if (rs.next()) {
                terceraRespuesta.setText(rs.getInt("OrdenRespuesta") + ". " + rs.getString("DescripcionRespuesta"));
                terceraRespuesta.putClientProperty("Id", rs.getInt("OrdenRespuesta"));;
                if (rs.getBoolean("EsCorrecta")) {
                    respuestaCorrecta = rs.getInt("OrdenRespuesta");
                }
            }
            if (rs.next()) {
                cuartaRespuesta.setText(rs.getInt("OrdenRespuesta") + ". " + rs.getString("DescripcionRespuesta"));
                cuartaRespuesta.putClientProperty("Id", rs.getInt("OrdenRespuesta"));
                if (rs.getBoolean("EsCorrecta")) {
                    respuestaCorrecta = rs.getInt("OrdenRespuesta");
                }
            }
        } else {
            repaintContent();
            showTotalPoints();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado = new javax.swing.JLabel();
        primeraRespuesta = new javax.swing.JButton();
        segundaRespuesta = new javax.swing.JButton();
        terceraRespuesta = new javax.swing.JButton();
        cuartaRespuesta = new javax.swing.JButton();
        txtDineroTotalGanado = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        enunciado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enunciado.setText("-");
        enunciado.setPreferredSize(null);

        primeraRespuesta.setBackground(new java.awt.Color(0, 102, 204));
        primeraRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        primeraRespuesta.setText("-");
        primeraRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        primeraRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        primeraRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        primeraRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraRespuestaActionPerformed(evt);
            }
        });

        segundaRespuesta.setBackground(new java.awt.Color(0, 102, 204));
        segundaRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        segundaRespuesta.setText("-");
        segundaRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        segundaRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        segundaRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        segundaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundaRespuestaActionPerformed(evt);
            }
        });

        terceraRespuesta.setBackground(new java.awt.Color(0, 102, 204));
        terceraRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        terceraRespuesta.setText("-");
        terceraRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        terceraRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        terceraRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        terceraRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceraRespuestaActionPerformed(evt);
            }
        });

        cuartaRespuesta.setBackground(new java.awt.Color(0, 102, 204));
        cuartaRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        cuartaRespuesta.setText("-");
        cuartaRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuartaRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuartaRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cuartaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartaRespuestaActionPerformed(evt);
            }
        });

        txtDineroTotalGanado.setEditable(false);
        txtDineroTotalGanado.setColumns(10);
        txtDineroTotalGanado.setText("00");

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cuartaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terceraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(primeraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDineroTotalGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(background, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enunciado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(background)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(primeraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(segundaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(terceraRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cuartaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtDineroTotalGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primeraRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraRespuestaActionPerformed
        int respuesta = (Integer) primeraRespuesta.getClientProperty("Id");
        if (respuesta == respuestaCorrecta) {
            numeroPreguntaActual++;
            try {
                // es necesario que este aqui debido a que también retorna una exception si la columna no existe
                dineroTotalGanado += valorPreguntaActual;
                txtDineroTotalGanado.setText("" + dineroTotalGanado);
                configuring();
            } catch (SQLException ex) {
                System.out.println("e" + ex.getMessage());
            }
        } else {
            repaintContent();
            showTotalPoints();
        }
    }//GEN-LAST:event_primeraRespuestaActionPerformed

    private void segundaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundaRespuestaActionPerformed
        int respuesta = (Integer) segundaRespuesta.getClientProperty("Id");
        if (respuesta == respuestaCorrecta) {
            numeroPreguntaActual++;
            try {
                // es necesario que este aqui debido a que también retorna una exception si la columna no existe
                dineroTotalGanado += valorPreguntaActual;
                txtDineroTotalGanado.setText("" + dineroTotalGanado);
                configuring();
            } catch (SQLException ex) {
                System.out.println("e" + ex.getMessage());
            }
        } else {
            repaintContent();
            showTotalPoints();
        }
    }//GEN-LAST:event_segundaRespuestaActionPerformed

    private void terceraRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceraRespuestaActionPerformed
        int respuesta = (Integer) terceraRespuesta.getClientProperty("Id");
        if (respuesta == respuestaCorrecta) {
            numeroPreguntaActual++;
            try {
                // es necesario que este aqui debido a que también retorna una exception si la columna no existe
                dineroTotalGanado += valorPreguntaActual;
                txtDineroTotalGanado.setText("" + dineroTotalGanado);
                configuring();
            } catch (SQLException ex) {
                System.out.println("exception = " + ex.getMessage());
                System.out.println("exception = " + ex.getSQLState());
            }
        } else {
            repaintContent();
            showTotalPoints();
        }
    }//GEN-LAST:event_terceraRespuestaActionPerformed

    private void cuartaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartaRespuestaActionPerformed
        int respuesta = (Integer) cuartaRespuesta.getClientProperty("Id");
        if (respuesta == respuestaCorrecta) {
            numeroPreguntaActual++;
            try {
                // es necesario que este aqui debido a que también retorna una exception si la columna no existe
                dineroTotalGanado += valorPreguntaActual;
                txtDineroTotalGanado.setText("" + dineroTotalGanado);
                configuring();
            } catch (SQLException ex) {
                System.out.println("e" + ex.getMessage());
            }
        } else {
            repaintContent();
            showTotalPoints();
        }
    }//GEN-LAST:event_cuartaRespuestaActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        numeroPreguntaActual = 1;
        dineroTotalGanado = 0;
        repaintContent();
        initComponents();
        configuring();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cuartaRespuesta;
    private javax.swing.JLabel enunciado;
    private javax.swing.JButton primeraRespuesta;
    private javax.swing.JButton segundaRespuesta;
    private javax.swing.JButton terceraRespuesta;
    private javax.swing.JTextField txtDineroTotalGanado;
    // End of variables declaration//GEN-END:variables
}
