spring.application.name=task
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=1234

# spring-boot-starter-data-jpa: Proporciona integración con JPA (Hibernate por defecto).
# mysql-connector-java: Driver JDBC para conectarse a MySQL.

# Configuration of Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true